/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/go-musicfox/go-musicfox/netease_bridge */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "main.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"

#line 3 "pcm_stream.go"

#include <stdlib.h>
#include <string.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern int NeteaseInit(char* dataDirC);
extern int NeteaseIsLoggedIn(void);
extern char* NeteaseGetUserInfo(void);
extern int NeteaseRefreshLogin(void);
extern char* NeteaseGetLikeSongs(int getAll);
extern char* NeteaseGetSongURL(long long int songId, char* quality);
extern char* NeteaseGetLastError(void);
extern void NeteaseFreeString(char* ptr);
extern int NeteaseSetCookie(char* cookieStr);
extern int NeteaseLikeSong(long long int songId, int like);
extern char* NeteaseGetLikeList(void);
extern char* NeteaseGetPersonalFM(void);
extern int NeteaseFMTrash(long long int songId);
extern char* NeteaseGetSongLyric(long long int songId);
extern int NeteaseLogout(void);
extern char* NeteaseQRGetKey(void);
extern char* NeteaseQRCheckStatus(void);
extern void NeteaseQRCancelLogin(void);
extern char* NeteaseGetUserPlaylists(int limit, int offset);
extern char* NeteaseGetPlaylistDetail(long long int playlistId);
extern char* NeteaseGetPlaylistSongs(long long int playlistId, int getAll);
extern char* NeteaseSearchPlaylistsByKeyword(char* keywordC);
extern char* NeteaseSearchSongs(char* keywordC, char* limitC);
extern long long int NeteaseCreatePcmStream(long long int songIdC, char* qualityC);
extern char* NeteaseGetPcmStreamInfo(long long int streamIdC);
extern int NeteaseReadPcmFrames(long long int streamIdC, void* bufferPtr, int framesToReadC);
extern int NeteaseSeekPcmStream(long long int streamIdC, long long int frameIndexC);
extern int NeteaseCanSeekPcmStream(long long int streamIdC);
extern void NeteaseClosePcmStream(long long int streamIdC);
extern int NeteaseIsPcmStreamReady(long long int streamIdC);
extern char* NeteaseGetPcmStreamError(long long int streamIdC);
extern double NeteaseGetCacheProgress(long long int streamIdC);
extern int NeteaseHasPendingSeek(long long int streamIdC);
extern long long int NeteaseGetPendingSeekFrame(long long int streamIdC);
extern void NeteaseCancelPendingSeek(long long int streamIdC);

#ifdef __cplusplus
}
#endif
